server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
management:
  security:
    enabled: false
hystrix:
  metrics:
    enabled: true
endpoints:
  actuator:
    enabled: true
  beans:
    enabled: true
  jmx:
    enabled: true
  jolokia:
    enabled: true
  metrics:
    enabled: true
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    enabled: true
  routes:
    enabled: true