eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
info:
  component: GateWay
hystrix:
  command:
      default:
        execution:
          isolation:
            strategy: THREAD

  metrics:
    enabled: true
endpoints:
  actuator:
    enabled: true
  beans:
    enabled: true
  jmx:
    enabled: true
  jolokia:
    enabled: true
  metrics:
    enabled: true
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    enabled: true
  routes:
    enabled: true
zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  prefix: /gate
  routes:
    rel:
      path: /cid/**
      sensitiveHeaders: null
      serviceId: app2
  semaphore:
    max-semaphores: 2000
  ribbon-isolation-strategy: thread
  
ribbon:
    ReadTimeout: 20000
    ConnectTimeout: 20000
#  OkToRetryOnAllOperations: true
#  MaxAutoRetries: 3
#  MaxAutoRetriesNextServer: 3
#  eureka:
#    enabled: true
    
server:
  port: 8763
  tomcat:
    max-threads: 20
management:
  security:
    enabled: false